### ISSUE TITLE
대회 정보 크롤링 봇 TODO

### ISSUE THREAD

**Issue by g0pher98** [RO-AD/road-discord-bot#1]
- [x] 데이터 크롤링 로직 개발
- [x] 크롤링 데이터 DB 저장 로직 개발
- [ ] 자동 크롤링(cron) 작업
- [ ] command 방식 말고 주기적으로 체크해서 메세지 보내도록 수정
